/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Thu Jan 19 18:00:48 2023.
 */

#include <string.h>

#include "GenericFastPacket.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int fp_generic_fast_packet_pack(
    uint8_t *dst_p,
    const struct fp_generic_fast_packet_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->chunk_id, 0u, 0x1fu);
    dst_p[0] |= pack_left_shift_u8(src_p->sequence_counter, 5u, 0xe0u);

    switch (src_p->chunk_id) {

    case 0:
        dst_p[1] |= pack_left_shift_u8(src_p->len_bytes, 0u, 0xffu);
        dst_p[2] |= pack_left_shift_u64(src_p->data_first_chunk, 0u, 0xffu);
        dst_p[3] |= pack_right_shift_u64(src_p->data_first_chunk, 8u, 0xffu);
        dst_p[4] |= pack_right_shift_u64(src_p->data_first_chunk, 16u, 0xffu);
        dst_p[5] |= pack_right_shift_u64(src_p->data_first_chunk, 24u, 0xffu);
        dst_p[6] |= pack_right_shift_u64(src_p->data_first_chunk, 32u, 0xffu);
        dst_p[7] |= pack_right_shift_u64(src_p->data_first_chunk, 40u, 0xffu);
        break;

    case 1:
        dst_p[1] |= pack_left_shift_u64(src_p->data, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u64(src_p->data, 8u, 0xffu);
        dst_p[3] |= pack_right_shift_u64(src_p->data, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u64(src_p->data, 24u, 0xffu);
        dst_p[5] |= pack_right_shift_u64(src_p->data, 32u, 0xffu);
        dst_p[6] |= pack_right_shift_u64(src_p->data, 40u, 0xffu);
        dst_p[7] |= pack_right_shift_u64(src_p->data, 48u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int fp_generic_fast_packet_unpack(
    struct fp_generic_fast_packet_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->chunk_id = unpack_right_shift_u8(src_p[0], 0u, 0x1fu);
    dst_p->sequence_counter = unpack_right_shift_u8(src_p[0], 5u, 0xe0u);

    switch (dst_p->chunk_id) {

    case 0:
        dst_p->len_bytes = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        dst_p->data_first_chunk = unpack_right_shift_u64(src_p[2], 0u, 0xffu);
        dst_p->data_first_chunk |= unpack_left_shift_u64(src_p[3], 8u, 0xffu);
        dst_p->data_first_chunk |= unpack_left_shift_u64(src_p[4], 16u, 0xffu);
        dst_p->data_first_chunk |= unpack_left_shift_u64(src_p[5], 24u, 0xffu);
        dst_p->data_first_chunk |= unpack_left_shift_u64(src_p[6], 32u, 0xffu);
        dst_p->data_first_chunk |= unpack_left_shift_u64(src_p[7], 40u, 0xffu);
        break;

    case 1:
        dst_p->data = unpack_right_shift_u64(src_p[1], 0u, 0xffu);
        dst_p->data |= unpack_left_shift_u64(src_p[2], 8u, 0xffu);
        dst_p->data |= unpack_left_shift_u64(src_p[3], 16u, 0xffu);
        dst_p->data |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
        dst_p->data |= unpack_left_shift_u64(src_p[5], 32u, 0xffu);
        dst_p->data |= unpack_left_shift_u64(src_p[6], 40u, 0xffu);
        dst_p->data |= unpack_left_shift_u64(src_p[7], 48u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

uint8_t fp_generic_fast_packet_chunk_id_encode(double value)
{
    return (uint8_t)(value);
}

double fp_generic_fast_packet_chunk_id_decode(uint8_t value)
{
    return ((double)value);
}

bool fp_generic_fast_packet_chunk_id_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t fp_generic_fast_packet_sequence_counter_encode(double value)
{
    return (uint8_t)(value);
}

double fp_generic_fast_packet_sequence_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool fp_generic_fast_packet_sequence_counter_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t fp_generic_fast_packet_len_bytes_encode(double value)
{
    return (uint8_t)(value);
}

double fp_generic_fast_packet_len_bytes_decode(uint8_t value)
{
    return ((double)value);
}

bool fp_generic_fast_packet_len_bytes_is_in_range(uint8_t value)
{
    return (value <= 223u);
}

uint64_t fp_generic_fast_packet_data_encode(double value)
{
    return (uint64_t)(value);
}

double fp_generic_fast_packet_data_decode(uint64_t value)
{
    return ((double)value);
}

bool fp_generic_fast_packet_data_is_in_range(uint64_t value)
{
    return (value <= 72057594037927935ull);
}

uint64_t fp_generic_fast_packet_data_first_chunk_encode(double value)
{
    return (uint64_t)(value);
}

double fp_generic_fast_packet_data_first_chunk_decode(uint64_t value)
{
    return ((double)value);
}

bool fp_generic_fast_packet_data_first_chunk_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}
