/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Thu Jan 19 18:00:48 2023.
 */

#ifndef GENERIC_FAST_PACKET_H
#define GENERIC_FAST_PACKET_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define FP_GENERIC_FAST_PACKET_FRAME_ID (0x19f000feu)

/* Frame lengths in bytes. */
#define FP_GENERIC_FAST_PACKET_LENGTH (8u)

/* Extended or standard frame types. */
#define FP_GENERIC_FAST_PACKET_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define FP_GENERIC_FAST_PACKET_CHUNK_ID_FIRST_CHUNK_CHOICE (0u)

/**
 * Signals in message GenericFastPacket.
 *
 * All signal values are as on the CAN bus.
 */
struct fp_generic_fast_packet_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t chunk_id;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t sequence_counter;

    /**
     * Range: 0..223 (0..223 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t len_bytes;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint64_t data;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint64_t data_first_chunk;
};

/**
 * Pack message GenericFastPacket.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fp_generic_fast_packet_pack(
    uint8_t *dst_p,
    const struct fp_generic_fast_packet_t *src_p,
    size_t size);

/**
 * Unpack message GenericFastPacket.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fp_generic_fast_packet_unpack(
    struct fp_generic_fast_packet_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fp_generic_fast_packet_chunk_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fp_generic_fast_packet_chunk_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fp_generic_fast_packet_chunk_id_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fp_generic_fast_packet_sequence_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fp_generic_fast_packet_sequence_counter_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fp_generic_fast_packet_sequence_counter_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fp_generic_fast_packet_len_bytes_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fp_generic_fast_packet_len_bytes_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fp_generic_fast_packet_len_bytes_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t fp_generic_fast_packet_data_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fp_generic_fast_packet_data_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fp_generic_fast_packet_data_is_in_range(uint64_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t fp_generic_fast_packet_data_first_chunk_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fp_generic_fast_packet_data_first_chunk_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fp_generic_fast_packet_data_first_chunk_is_in_range(uint64_t value);


#ifdef __cplusplus
}
#endif

#endif
